### ISSUE TITLE
runtime error using cupy in multiprocessing.pool

### ISSUE THREAD

**Issue by ppaanngggg** [chainer/chainer#1087]
When I use data-parallel multi gpu training. I want to use multiprocessing.pool to speed up feeding commands to multi gpus, so I operate models on and variables of each gpu on each thread. However I get error like this:

> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/home/xiaohei/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/home/xiaohei/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "/home/xiaohei/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
>     task = get()
>   File "cupy/cuda/runtime.pyx", line 101, in cupy.cuda.runtime.CUDARuntimeError.__init__ (cupy/cuda/runtime.cpp:1629)
> TypeError: ('an integer is required', <class 'cupy.cuda.runtime.CUDARuntimeError'>, (u'cudaErrorInitializationError: initialization error',))

**Comment by delta2323** [comment]
Thank you for reporting! We had been reported the similar problem in Japanese forum (the version is older). But we have not found the cause of this error so far. Can you make a minimal code that causes this problem?

**Comment by ppaanngggg** [comment]
@delta2323 Many thank you. I will offer a mini code later. After that, I use multi standing processes and communicating with each other to implement similar function, but much coding then before.

**Comment by ppaanngggg** [comment]
```
import chainer.links as L
from chainer import Variable, cuda
import cupy
from multiprocessing import Process

x1_data = cupy.ones((1,5), cupy.float32)
x2_data = cupy.ones((1,5), cupy.float32)

x1 = Variable(cuda.to_gpu(x1_data, 1))
x2 = Variable(cuda.to_gpu(x2_data, 2))

model = L.Linear(5,2)
model1 = model.copy().to_gpu(1)
model2 = model.copy().to_gpu(2)

def f(x, model):
    print model(x).data

p1 = Process(target=f, args=(x1,model1,))
p2 = Process(target=f, args=(x2,model2,))

p1.start()
p2.start()

p1.join()
p2.join()
```

Then, error log like this:
-- Process Process-1:
Traceback (most recent call last):
  File "/home/xiaohei/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/xiaohei/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 17, in f
    print model(x).data
  File "/home/xiaohei/usr/lib/python2.7/site-packages/chainer/links/connection/linear.py", line 65, in __call__
    return linear.linear(x, self.W, self.b)
  File "/home/xiaohei/usr/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 81, in linear
    return LinearFunction()(x, W, b)
  File "/home/xiaohei/usr/lib/python2.7/site-packages/chainer/function.py", line 122, in __call__
    with cuda.get_device(*in_data):
  File "cupy/cuda/device.pyx", line 61, in cupy.cuda.device.Device.__enter__ (cupy/cuda/device.cpp:1467)
  File "cupy/cuda/runtime.pyx", line 131, in cupy.cuda.runtime.getDevice (cupy/cuda/runtime.cpp:2054)
  File "cupy/cuda/runtime.pyx", line 110, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:1821)
CUDARuntimeError: cudaErrorInitializationError: initialization error
Process Process-2:
Traceback (most recent call last):
  File "/home/xiaohei/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/xiaohei/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 17, in f
    print model(x).data
  File "/home/xiaohei/usr/lib/python2.7/site-packages/chainer/links/connection/linear.py", line 65, in __call__
    return linear.linear(x, self.W, self.b)
  File "/home/xiaohei/usr/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 81, in linear
    return LinearFunction()(x, W, b)
  File "/home/xiaohei/usr/lib/python2.7/site-packages/chainer/function.py", line 122, in __call__
    with cuda.get_device(*in_data):
  File "cupy/cuda/device.pyx", line 61, in cupy.cuda.device.Device.__enter__ (cupy/cuda/device.cpp:1467)
  File "cupy/cuda/runtime.pyx", line 131, in cupy.cuda.runtime.getDevice (cupy/cuda/runtime.cpp:2054)
  File "cupy/cuda/runtime.pyx", line 110, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:1821)
CUDARuntimeError: cudaErrorInitializationError: initialization error

**Comment by delta2323** [comment]
Thank you for the code. I can reproduce your error (with Python 2.7.9, CUDA 7.5). So we will investigate the problem.

**Comment by ppaanngggg** [comment]
@delta2323 Many thank you, :D

I use Python 2.7.11, CUDA 7.5, CUDNN 4

**Comment by Fhrozen** [comment]
Good Night.

I also have the same problem and i tried to execute using multiprocessing and multithreading in both cases was not possible. in the case of processing i tried with the same code as @ppaanngggg, and also try to point at a external function:
`
def unwrap_zerograds(arg, **kwarg):
      return Model.ZeroGradsOne(*arg, **kwarg)
`
using inside and outside a class with this instruction:
`processes = [mP.Process(target=unwrap_zerograds, args=((self, i),)) for i in range(0, len(self.Networks))]`

and i got the same error:

> `Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nelson/Tasks/Task0004/chainer_net.py", line 240, in ZeroGradsOne
    self.Networks[i].zerograds()
  File "/usr/local/lib/python2.7/dist-packages/chainer/link.py", line 530, in zerograds
    super(Chain, self).zerograds()
  File "/usr/local/lib/python2.7/dist-packages/chainer/link.py", line 318, in zerograds
    param.zerograd()
  File "/usr/local/lib/python2.7/dist-packages/chainer/variable.py", line 214, in zerograd
    with cuda.get_device(self.data) as dev:
  File "cupy/cuda/device.pyx", line 61, in cupy.cuda.device.Device.__enter__ (cupy/cuda/device.cpp:1540)
  File "cupy/cuda/runtime.pyx", line 131, in cupy.cuda.runtime.getDevice (cupy/cuda/runtime.cpp:2083)
  File "cupy/cuda/runtime.pyx", line 110, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:1865)
CUDARuntimeError: cudaErrorInitializationError: initialization error
`
i tried this on a 1-gpu machine in order to scale for a multigpu and speed up the feeding and processing but i got this error.

I was wondering if you found any solution.

**Comment by anaruse** [comment]
This is probably because you tried to share GPU' device memory among multiple processes.  Any device memory allocated by one process cannot be read/written from the other processes (except using CUDA IPC APIs).

**Comment by jekbradbury** [comment]
The problem here is that a CUDA API handle that has been initialized in one process cannot be used in another process. This means that if you use `multiprocessing`, you cannot do ANYTHING with CUDA/cupy before forking your processes. You must do everything CUDA-related in your worker processes after forking, even initialization or setting a random seed.

**Comment by tungld** [comment]
Hi, it seems that there is no clear answer for the problem. Any solution to the program given by @ppaanngggg above?

**Comment by ppaanngggg** [comment]
I use SharedArray to share numpy between processes. Creating cupy array in different processes is impossible.

**Comment by beam2d** [comment]
There is not easy solution for passing a CuPy array to another process in Py2 (not in Windows), since the child process is always a fork of the parent, and forking a process with a CUDA context does not work correctly.

If you can use Py3, there is a solution: using 'spawn' or 'forkserver' mode of multiprocessing (the latter is more efficient). It makes the child process not reuse the CUDA context used in the parent process. The fixed code is as follows (be careful not to include any CUDA-related code directly in the global scope before setting the forking mode). Note that, in Windows, Py2 already uses 'spawn' mode for invoking a child process (because there is no counterpart of 'fork' in Windows API), and so the following code may run in Py2 of Windows.

```python
import chainer.links as L
from chainer import Variable, cuda
import cupy
import multiprocessing
from multiprocessing import Process

def f(x, model):
    print(model(x).data)

if __name__ == '__main__':
    multiprocessing.set_start_method('forkserver')

    x1_data = cupy.ones((1,5), cupy.float32)
    x2_data = cupy.ones((1,5), cupy.float32)

    x1 = Variable(cuda.to_gpu(x1_data, 1))
    x2 = Variable(cuda.to_gpu(x2_data, 2))

    model = L.Linear(5,2)
    model1 = model.copy().to_gpu(1)
    model2 = model.copy().to_gpu(2)

    p1 = Process(target=f, args=(x1,model1,))
    p2 = Process(target=f, args=(x2,model2,))

    p1.start()
    p2.start()

    p1.join()
    p2.join()
```

Be careful that it actually passes the GPU array between processes, but is not zero-copy. Multiprocessing first pickles each argument, passes them to another process, unpickles them, and passes them to the target function. CuPy ndarray supports pickling, but it actually first copies the array to NumPy ndarray and pickles it (and do the inverse in unpickling). So passing a CUDA array in this way is slow due to the host-to/from-device copy and pickling, but it works.

**Comment by ppaanngggg** [comment]
So I use SharedArray to hold numpy array，which can share memory between processes. Pickling and unpickling are too slow.

**Comment by lpf-gavin** [comment]
the same problem occurred

**Comment by Joevaen** [comment]
> The problem here is that a CUDA API handle that has been initialized in one process cannot be used in another process. This means that if you use `multiprocessing`, you cannot do ANYTHING with CUDA/cupy before forking your processes. You must do everything CUDA-related in your worker processes after forking, even initialization or setting a random seed.

Can you explain in detail? Do you have a demo code to solve it?

**Comment by ginward** [comment]
I am having a similar issue with the following code: 


`from joblib import Parallel, delayed
from itertools import cycle
import cupy
import spacy
from thinc.api import set_gpu_allocator, require_gpu


def chunker(iterable, total_length, chunksize):
    return (iterable[pos: pos + chunksize] for pos in range(0, total_length, chunksize))

def flatten(list_of_lists):
    "Flatten a list of lists to a combined list"
    return [item for sublist in list_of_lists for item in sublist]

def process_entity(doc):
    super_word_ls = []
    for s in doc.sents:
        word_ls = []
        for t in s:
            if not t.ent_type_:
                if (t.text.strip()!=""):
                    word_ls.append(t.text)
            else:
                word_ls.append(t.ent_type_)
        if len(word_ls)>0:
            super_word_ls.append(" ".join(word_ls))
    return " ".join(super_word_ls)

def process_chunk(texts, rank):
    print(rank)
    with cupy.cuda.Device(rank):
        set_gpu_allocator("pytorch")
        require_gpu(rank)
        nlp = spacy.load("en_core_web_trf")
        preproc_pipe = []
        for doc in nlp.pipe(texts, batch_size=20):
            preproc_pipe.append(process_entity(doc))
        rank+=1
        return preproc_pipe


def preprocess_parallel(texts, chunksize=100):
    executor = Parallel(n_jobs=2, backend='multiprocessing', prefer="processes")
    do = delayed(process_chunk)
    tasks = []
    gpus = list(range(0, cupy.cuda.runtime.getDeviceCount()))
    rank = 0
    for chunk in chunker(texts, len(texts), chunksize=chunksize):
        tasks.append(do(chunk, rank))
        rank = (rank+1)%len(gpus)
    result = executor(tasks)
    return flatten(result)

preprocess_parallel(texts = ["His friend Nicolas J. Smith is here with Bart Simpon and Fred."]*100, chunksize=50)
`

**Comment by BramVanroy** [comment]
Is it correct that this is closed but not solved? The corresponding PR seems to add a warning and urges us to avoid using parallel but I do not think this is solved. Can anyone confirm?

**Comment by BramVanroy** [comment]
@ginward I saw your post on [StackExchange](https://datascience.stackexchange.com/questions/98149/does-spacy-support-multiple-gpus). What did it for me was using spawn instead of fork, as you mentioned. Do you know _why_ that works though?
