### ISSUE TITLE
CUDA kernel compilation fails with GCC 6

### ISSUE THREAD

**Issue by vberger** [chainer/chainer#1569]
With GCC 6, C++ version used defaults to C++11, with breaks cuda kernel compilation.

To use chainer with GCC 6, a fix is to add

```
options += ('-Xcompiler', '--std=c++98')
```

to the `compile_with_cache` function in `cupy/cuda/compiler.py`.

It would be nice to integrate this (probably in a more clean way) in the distributed package, so that users like me with distributions shipping GCC 6 don't have to patch at each upgrade.

I believe such a change would be fully backwards-compatible, as `--std=c++98` has been a valid option for GCC for years.

**Comment by gwtnb** [comment]
Thank you for reporting. Although GCC 6 is not supported officially by CUDA 7.5 and CUDA 8.0RC, I agree that it is useful if Chainer works with GCC 6.

> `options += ('-Xcompiler', '--std=c++98')`

Just adding this statement may break backward compatibility because `compile_with_cache` receives options (e.g. incompatible with `--std=c++11`). Instead of hard-coding, we should modify cupy to allow users to specify compiler options.

> With GCC 6, C++ version used defaults to C++11

GCC 6 uses C++14 by default.

**Comment by soramichi** [comment]
Hi, I found that for CUDA 8.0 (nvcc 8.0) and GCC 6.3, an extra hack is required to make chainer work.

What exactly needed is to comment-out line 119 of `/usr/local/cuda/include/host_config.h` as follows:
```C
#if __GNUC__ > 5

//#error -- unsupported GNU version! gcc versions later than 5 are not supported!                                                                                                     

#endif /* __GNUC__ > 5 */
```

This hack originally comes from a wiki page of caffe:
https://github.com/BVLC/caffe/wiki/GeForce-GTX-1080,---CUDA-8.0,---Ubuntu-16.04,---Caffe
