### ISSUE TITLE
Replace function with chainer.Function in docstrings

### ISSUE THREAD

**Issue by gwtnb** [chainer/chainer#1587]
Some arguments of functions are wrongly typed in docstrings. For example, this [`activation`](https://github.com/pfnet/chainer/blob/v1.14.0/chainer/links/connection/mlp_convolution_2d.py#L30) argument's type should be `chainer.Function` but it is `function`. 

This generates wrong links to http://docs.chainer.org/en/stable/reference/function_hooks.html#module-chainer.function in documents.

**Comment by hvy** [comment]
I agree that this should be fixed, since a wrong urls is confusing to the reader. However, more generally, we cannot simply replace `function` with `~chainer.Function` since some arguments are meant to be general Python functions, e.g. https://docs.chainer.org/en/stable/reference/generated/chainer.gradient_check.numerical_grad.html?highlight=gradient_check

**Comment by hvy** [comment]
In the case of the arg being a Python function, we could either reference the Python docs for the function definition https://docs.python.org/3/reference/compound_stmts.html#function-definitions or maybe link to this page https://docs.chainer.org/en/stable/reference/functions.html by simply changing `function` to `functions`.

**Comment by hvy** [comment]
Bump.

**Comment by kmaehashi** [comment]
Fixed via #4052
