### ISSUE TITLE
Caffe import implementation choices

### ISSUE THREAD

**Issue by fchollet** [chainer/chainer#166]
@beam2d maybe you can shed some light on this.

You decided to start supporting Caffe models by copying into your codebase the 5,000 LOC file [`caffe_pb2`](https://github.com/pfnet/chainer/blob/master/chainer/functions/caffe/caffe_pb2.py) generated by the compiler when building Caffe. It represents a significant fraction of your codebase, and it is not meant as a file you can just drop in a new project (it is supposed to be generated and likely customized when building Caffe on a new system).

Why did you make this choice?

Why not use `pycaffe`, the Python Caffe wrapper that is the "official" way to interact with Caffe in Python? Wouldn't this be much cleaner? Any specific reason why you could not / did not want to go that way?

**Comment by beam2d** [comment]
Thank you for the suggestion about using pycaffe.
The only reason is that Caffe is more difficult to install than Chainer. Many users pay days to install Caffe. This is because Caffe is written in C++ and using many external libraries in order to make it very fast. I think this cost is necessary for the speed and portability of Caffe. On the other hand, Chainer's installation is done by pip command. I want to keep this simplicity.

Though, I agree that including the compiled pb file into the codebase is very ugly. If there are a smarter way to extract the model parameters without depending on Caffe, I want to adopt it.

Note that the Caffe model support of v1.1.0 only aims at supporting the reference models provided by BVLC team. Supporting arbitrary Caffe models learned by users should be done by other future issues/PRs, where we may use the original pycaffe to extract the model parameters.

**Comment by fchollet** [comment]
Thanks for the clarification. Have you considered using `caffe_pb2.py` as a base to create a new, clean Python module that would implement a Caffe-independent interface to Caffe models? Such a module could be installed via pip and would not burden the Chainer install process.

If you're interested in this approach we could collaborate on doing this; I'm interested in a clean way to access Caffe models without having to install Caffe (and without trashing my codebase with a huge blob of unrelated code).

**Comment by beam2d** [comment]
I did not consider such way, though I used such package if already existed, of course. I'm interested in this approach.

**Comment by fchollet** [comment]
The minimum viable version of this would be to package `caffe_pb2.py` as a github repo and PyPI package, and list the package as a dependency of Chainer while removing `caffe_pb2.py` from the Chainer codebase. What are your thoughts on this?

The code of the package can be cleaned up and improved later (especially if it turns out not to work on certain systems).

**Comment by beam2d** [comment]
That's appropriate as the first step. I think we should involve the Caffe community at some point (it may be done after the above stuff, though).

**Comment by fchollet** [comment]
Action items:
- pick a name (I suggest `xpresso`, which is free; `espresso` is obviously already taken on PyPI)
- create the repo
- add appropriate info about the nature and purpose of the code
- release on PyPI

**Comment by beam2d** [comment]
Thank you for collecting the AIs. It seems a very similar name (Expresso) is used for another Caffe-related project, which could be confusing. https://github.com/BVLC/caffe/wiki/Related-Projects
I'm thinking for another name.

**Comment by pranv** [comment]
Cappuccino

**Comment by pranv** [comment]
@fchollet, protocol buffers are not significantly customized to the environment even though they are compiled. The compilation results in creation of usable objects from a specification. One can install Google Protocol Buffers library, get the Caffe.proto file from Caffe repo and manually compile it. 
Maybe a shell script to do that could help prevent thrashing of your codebase
