### ISSUE TITLE
Make chainer faster ( for small networks )

### ISSUE THREAD

**Issue by bordingj** [chainer/chainer#1771]
For very small networks most of the time is spend on internal chainer stuff which could be optimized. 

When I time some of my small cpu networks, the majority of the time is actually spend locally in the `__call__` method of functions. This has actually become worse after introducing `local_function_hooks` and allowing functions to be called on non-Variables. 

 I have a couple of suggestions for making chainer faster in these settings. 
- cythonize `variable.py`, `function.py`, `flag.py` and `cuda.py` and make `Variable` and `Function` cython extension types.
- avoid calling `int(os.environ.get('CHAINER_TYPE_CHECK', '1')) != 0` every time a new function instance is created.
- go back to only allowing functions to be calling on Variables (the outputs are always Variables anyway).
- avoid creating an `OrderedDict`  (and updating it) if the function doesnt have any function hooks.
- use cpython functions `PyTuple_New`, `PyTuple_SET_ITEM`, `Py_INCREF` with for-loops in cython for creating new tuples instead of creating list comprehesions and making tuple's of these (in `Variable.__call__`and in `Variable.backward` ).
  - Checking the device, the flags and the ranks of the inputs and making a new `in_data` tuple in the `Variable.__call__` method can actually be done in a single for loop with cython. Currently, 8 loops is performed in order to do this ( `cuda.get_device(*in_data)` counts as 2 and `flag.aggregate_flags([x.volatile for x in inputs])` counts as 3 ). Likewise, the `self.outputs` and `ret` tuples can be build in a single loop with cython.
- Make volatile flags integers instead of classes. 
- By seperating functions from learnables in Functions and Links we paid a performance penalty, because every gradient of the learnables are now being newly created for every function call (very expensive with cupy), and then accumulated later, instead of being accumulated on the fly in the `Function.backward` methods. It would be cool if we could avoid this for learnables somehow (this is a big issue for RNNs on the gpu).

I think that backward-compatibility could be sacrificed for speed. Chainer is still young. 
If chainer is going to be able to compete with other frameworks such as Tensorflow, Theano and Torch we need more speed in my opinion.

Btw, if you cythonize variable.py you need to change `del gxs` to `gxs = None` ( this is also better practice in my opinion) in the `Variable.backward` method.

**Comment by beam2d** [comment]
Thank you for proposing how to make the core features faster. We are also very interested in the performance of the logic part of Chainer, because it is often the bottleneck of the performance for networks with many small operations even in using GPU, as you know.

I'm interested in your proposal. Have you taken any profiles to confirm that these fixes would be effective? We want to be careful on adding changes that break the compatibility and/or increase the maintenance cost, so I want to add minimum changes to effectively improve the performance.

**Comment by bordingj** [comment]
In the next couple of weeks I will try to add these changes, and do some testing.
Also, I will add the possibility to call `Function.forward` with `output_buffer` arrays and `Function.backward` with `grad_inputs_buffer` arrays. Using preallocated buffers should speed up GPU computations alot. A buffer should of course only be written to once per forward/backward call.

**Comment by bordingj** [comment]
Btw...  `x._grad += gx` in `Variable.backward` could have been done in `Function.backward`. By doing the accumulation in `Function.backward` we would save memory and get speedups by using something similar to `skcuda.linalg.add_dot` in `linear` for example. In my experience, using `skcuda.linalg.add_dot(a, b, c)` is alot faster than `c += cupy.dot(a,b)` (because the blas operation is an add_dot operation ).

**Comment by jekbradbury** [comment]
This last point is very insightful. I was staring at the Visual Profiler and wondering how to fix the speed issues I was having (all of the small `cupy_add` calls on the right are from `x._grad += gx`). I think you've figured it out! Let me know if you want help with any part of this project (my github username at gmail).

![screenshot from 2016-10-18 12 17 26](https://cloud.githubusercontent.com/assets/11729078/19492763/dfb6b776-952c-11e6-9983-4a1aa8c42bd8.png)

**Comment by jekbradbury** [comment]
On second thought, your proposal likely wouldn't help with this particular use case (these `cupy_add` calls accumulate gradients from the backwards pass of a concatenation operation)

**Comment by honnibal** [comment]
Here is the top part of a  profile from a bidirectional LSTM network on GPU.

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   584000   47.340    0.000   47.340    0.000 {method 'dot' of 'cupy.core.core.ndarray' objects}
      196   46.522    0.237  156.844    0.800 variable.py:322(backward)
    39200   26.160    0.001   29.153    0.001 lstm.py:101(backward)
   542961   15.857    0.000  193.889    0.000 function.py:154(__call__)
    19600   14.929    0.001   22.543    0.001 bilinear.py:76(backward)
20548926/7520958   13.387    0.000   34.667    0.000 type_check.py:220(_eval_expr)
 52762995   11.025    0.000   13.850    0.000 {isinstance}
      421    8.545    0.020    8.580    0.020 {cupy.core.core.array}
    19796    8.319    0.000    8.322    0.000 elu.py:41(backward_gpu)
  1340725    7.604    0.000   15.523    0.000 collections.py:50(__init__)
```

**Comment by jekbradbury** [comment]
@honnibal:
1. Make sure to turn off typecheck (the core devs haven’t yet merged a fix that would make typecheck much faster; until then it should only be on for debugging)
2. A CPU profile will be misleading because time will be spent in whatever calls block due to GPU data from asynchronously spawned kernels not being available yet. That is, if you create some cupy arrays, call dot on them, and then print() the first element of the result a CPU profile will say your script spent 99% of time in something like ndarray.getitem.
3. This is only true for “big networks” like an ordinary LSTM of decent batch and hidden size. This thread is about “small networks” where each individual GPU kernel is so fast that the Python runtime can’t keep up and spawn the next one quickly enough to keep the GPU utilization at 100%. While there are still optimizations possible at full GPU utilization, they won’t look like the options proposed in this thread, which are targeted at situations and networks that can’t currently achieve 100% GPU utilization with Chainer.

**Comment by honnibal** [comment]
1. Thanks. I was wondering why the library was so slow — I was getting ready to roll up my sleeves and fix it :)

2. Good point.

3. This is basically the situation most of my NLP code has been in, especially when using sparse linear models. You have to do a lot of small things, so the whole program has to be fast.

What's worked for me in spaCy is to have a "pure Cython" under-layer that strictly speaks structs, raw pointers, vectors etc. I have a CPU feed-forward network in this style, although it's never been cleaned up for release. Example: https://github.com/explosion/thinc/blob/master/thinc/neural/forward.pyx#L116

I think a good solution for the `ndarray` class would to have a `cdef cppclass` that held all the data. The parent, Python-visible `cdef class` would then only hold a pointer to this implementation class. Internally, you could pass this pointer around instead of the Python object.

Here's a simple example of this pattern, in my hash table:

https://github.com/explosion/preshed/blob/master/preshed/maps.pxd

Here's a more complicated example in the state object. This one uses the `cppclass` trick. This was crucial to releasing the GIL for spaCy's parser.

https://github.com/explosion/spaCy/blob/master/spacy/syntax/_state.pxd
https://github.com/explosion/spaCy/blob/master/spacy/syntax/stateclass.pxd
