### ISSUE TITLE
wscale doesn't have backward compatibility

### ISSUE THREAD

**Issue by dsanno** [chainer/chainer#1806]
The wscale behavior of some links is different between chainer v1.17.0 and v1.8.2 as follows:

chainer v1.17.0

```
>>> from chainer import links as L
>>> import math
>>> fc = L.Linear(100, 100, wscale=math.sqrt(2))
>>> fc.W.data.std()
0.11967628
```

chaier v1.8.2

```
>>> from chainer import links as L
>>> import math
>>> fc = L.Linear(100, 100, wscale=math.sqrt(2))
>>> fc.W.data.std()
0.14099795
```

In v.1.17.0(maybe v1.9.0 and later) `W` attribute is initialized by `HeNormal` with scale=(math.sqrt(wscale)/ numpy.sqrt(2)) when `initializeW` is None.
I think it is correct to initialize using scale=wscale/numpy.sqrt(2)

This is caused by `initializers._get_initializer` parameter in each Link constructor.
For example in `__init__` of `Linear`

```
        # For backward compatibility, the scale of weights is proportional to
        # the square root of wscale.
        self._W_initializer = initializers._get_initializer(
            initialW, math.sqrt(wscale))
```

I think this should be `initializers._get_initializer(initialW, wscale)`

**Comment by beam2d** [comment]
Thank you for reporting such a serious problem! I'm surprised that such an issue has been left overlooked. Maybe the problem is broken down into the following two.

1. The compatibility is broken. v1.9.0 was released almost 5 months ago, though, so it would be difficult to solve the compatibility issue (fixing it will introduce incompatibility against recent versions).
2. The current implementation does not follow the documentation (users expect that `wscale` directly scales the weight, while it actually scales through sqrt). In that sense, the current implementation can be treated as a bug, though the compatibility issue would be more serious, since fixing it breaks the reproducibility of existing user codes.

We need further discussions on this issue.

Another point is why this problem occurs: I think this is because the current interface of specifying how to initialize parameters is too complicated mainly due to historical reasons. The interface should ideally be cleaned up.
