### ISSUE TITLE
numpy.argmax and cupy.argmax behave differently when input is 1D

### ISSUE THREAD

**Issue by soramichi** [chainer/chainer#2077]
`numpy.argmax` returns `numpy.int64` when the input array is 1-dimensional,
but `cupy.argmax` returns a `cupy.core.core.ndarray` whose (only) element is the answer.

```
numpy.__version__   # '1.11.3'
chainer.__version__ # '1.19.0'

numpy.argmax(numpy.array([1,2,3])) # 2
cupy.argmax(cupy.array[1,2,3]))    # array(2)

type(numpy.argmax(numpy.array([1,2,3]))) # <class 'numpy.int64'>
type(cupy.argmax(cupy.array[1,2,3])))    # <class 'cupy.core.core.ndarray'>
```

P.S.1
I found related functions (`max`, `min`, `argmin`) also behave differently in numpy and cupy.
Sorry for bothering you if these behaviors are as expected. 

P.S.2
The reason why this passes the test  cases: in `cupy.testing.assert_allclose()`,
`actual` (the result of `cupy.max`) and `desired` (the result of `numpy.max`) are
both wrapped by `cupy.asnumpy()`. It turns both an integer and an 1-D array
into an 1-D array (`cupy.asnumpy(1) == cupy.asnumpy(cupy.array(1)) # => True`).

**Comment by beam2d** [comment]
Sorry for late reply, but this behavior is expected. We cannot have `numpy.int64` (nor any other numpy scalar types) on GPUs, while moving data between GPUs to CPU is costly. Thus, we decided to use zero-dimensional arrays in CuPy as the alternative of scalars in NumPy. It also makes the overall CuPy implementation much simpler because we do not have to deal with different types as holders of GPU data.

I will close this issue because the different behavior is expected one. Please open a new issue if you find it inconvenient and feel that CuPy should provide distinction between arrays and scalars like NumPy.
