### ISSUE TITLE
Re-implement the current slstm as TreeLSTM

### ISSUE THREAD

**Issue by keisuke-umezawa** [chainer/chainer#2592]
As mentioned in #2460,
current slstm is different from the papers.
The implementation is very similar to TreeLSTM model (https://arxiv.org/pdf/1503.00075.pdf).
So, please re-implement as TreeLSTM.

> Second issue does not obligate to this PR. Current implementation of slstm seems different from formulation in the cited paper (https://arxiv.org/pdf/1503.04881.pdf) and little similar to other TreeLSTM model (https://arxiv.org/pdf/1503.00075.pdf) but also different from it. (I skipped the details here, but I can describe them if needed.) If this is also confirmed by others, it looks good to fix or re-implement as TreeLSTM, which is more cited and popular in NLP, toward Chainer v2. What do you (and other reviewers) think?

**Comment by soskek** [comment]
Thank you for making the issue!
I am grad of the birth of TreeLSTM. However, I am not sure if Chainer's dev policy allows such replacement (discontinuing slstm and making newly TreeLSTM) or not, due to backward compatibility (between v1 and v2).
If not, it looks good to just fix a bug of slstm and make TreeLSTM as a separate issue or forgotten.

(By the way, please fix a typo in the title of this issue; current lstm -> current slstm.)

**Comment by soskek** [comment]
Even if we just fix slstm, the consistency of its interface would be broken, because formal slstm needs complicated connections and to be a link rather than a function.
FYR, I wrote a pseudo code of slstm and TreeLSTM using only existing primitive functions and links.Linear.
https://gist.github.com/soskek/db09c5c75d6e7d4254f80ec5ec9de6d1

**Comment by soskek** [comment]
I discussed this issue with @unnonouno offline.
Then, I will fix slstm simply as a link, using the code above without specific code of cuda. It changes the interface of existing slstm. (So, in #2460, modification of doc of slstm can be short temporally.)
I will insert `chainer.utils.experimental('chainer.links.s.slstm.py')` for showing that it is experimental API.
TreeLSTM variants (N-ary TreeLSTM and Child-Sum TreeLSTM) remain not implemented. I hope that it will be implemented if someone needs more or has time.

**Comment by unnonouno** [comment]
I'm sorry. The current implementation is my mistake. BTW, in my experiment it works well in Stanford sentiment treebank. Let's make it deprecated, and make a newer implementation to avoid confusing situation.

**Comment by soskek** [comment]
I agree with you because slstm in the paper is not sufficiently formalized and has some ambiguous points, e.g., behavior at a leaf node.
I will newly make TreeLSTM toward Chainer v2 instead of slstm.

**Comment by soskek** [comment]
New Tree LSTMs have been implemented.
