### ISSUE TITLE
How can I limit the number of active threads?

### ISSUE THREAD

**Issue by cenyk1230** [chainer/chainer#2634]
When I execute the codes which use chainer framework in a linux server, it occupies most of the cpu threads automatically. But the server is shared among several people, I should not use too many cpu threads. So how can I limit the number of active threads when using chainer framework?
Thanks a lot!

**Comment by unnonouno** [comment]
Actually chainer itself does not use multi-thread.
Maybe it is problem of BLAS library NumPy uses. For example, OpenBLAS, one of the famous BLAS library, uses all threads by default. You can change the number of threads it uses with `OPENBLAS_NUM_THREADS` environment variable. BLAS library depends on your environment. If you use Intel MKL, you can control the number of threads with `MKL_NUM_THREADS`. Please check your environment.

**Comment by cenyk1230** [comment]
It does work after setting the OPENBLAS_NUM_THREADS environment variable. Thank you so much!

**Comment by soramichi** [comment]
Hi,

I think it is better for chainer to automatically set this kind of environment variables before calling any BLAS functions, because using all the cores (OpenBLAS default) does not yield the best performance in many cases (or almost all cases if the number of cores is large). From my experience, using only 4 cores or less is sufficient for many cases.
