### ISSUE TITLE
Update "Comparison with Other Frameworks"

### ISSUE THREAD

**Issue by mitmul** [chainer/chainer#2685]
This content has been obsolete already. Should be updated.
http://docs.chainer.org/en/stable/comparison.html

Recent framework missing in the current comparison table:

- Tensorflow
- MXNet
- CNTK
- Neon
- DeepLearning4j
- DyNet
- Darknet
- PyTorch
- Caffe2

**Comment by delta2323** [comment]
I agree that to the comparison with other framework is useful for users because it encourages a better choice of frameworks that meet their needs. And it is also important for Chainer itself to make the developer team be aware the standpoint of Chainer. One thing I am concerning is, as you imagine, the maintenance cost to keep track of the latest information of other frameworks. Do you have an idea how often we should update the table?

**Comment by jekbradbury** [comment]
I can write up an updated version of this table this weekend (I've spent a lot of time with several of these frameworks so I may be able to give more of an outsider's view than the core dev team).

**Comment by delta2323** [comment]
@jekbradbury Thank you for suggestion. Your point of view will be helpful for fair and objective comparison. Are you thinking of sending a PR? I would like to know your idea about how to proceed.

**Comment by jekbradbury** [comment]
Yes, I'll send a PR.

**Comment by delta2323** [comment]
Great, I am waiting for your PR.
