### ISSUE TITLE
Why mixed Variable to function must report error:  ON and OFF flags cannot be mixed

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#2753]
this issue original from issue : https://github.com/amasky/ram/issues/3
I am a researcher currently using your excellent framework chainer!
I found in **some case, I must stop gradient flow from one component of Function**, But allow gradient flow from other component of Function.
Just like below:
```
l = Variable(np.array([3,0],dtype=np.float32),volatile=False)
c = Variable(np.array([2,1],dtype=np.float32),volatile=True)
import chainer.functions as F
F.sum(c+l)
```
it will report error:
ValueError: ON and OFF flags cannot be mixed.

**Comment by delta2323** [comment]
The `volatile` attribute of `Variable` is used to determine if we should construct a computational graph or not when `Variable`'s are fed to a Chainer function. If some input variables are `volatile=on` and some are `off`, the function cannot determine if it should build a computational graph or not.

In order to stop the gradient flow, there are at least two ways to do so:
(1) Change `volatile` attribute manually.
```
x = Variable(np.array(...), volatile='on')
y = f(x)



```

**Comment by delta2323** [comment]
The `volatile` attribute of `Variable` is used to determine if we should construct a computational graph or not when `Variable`'s are fed to a Chainer function. If some input variables are `volatile=on` and some are `off`, the function cannot determine if it should build a computational graph or not.

In order to stop the gradient flow, there are at least two ways to do so:
(1) Change `volatile` attribute manually:
```
x = Variable(np.array(...), volatile='on')
y = f(x)
y.volatile = 'off'
z = Variable(np.array(...), volatile='off')
w = g(y, z)
```

(2) Use [`Variable.unchain_backward`](https://github.com/pfnet/chainer/blob/master/chainer/variable.py#L478)
```
x = Variable(np.array(...), volatile='off')
y = f(x)
z = Variable(np.array(...), volatile='off')
w = g(y, z)
y.unchain_backward()
```

In either case, `w.backward()` calculates gradient of w w.r.t each variable. But the error does not propagate to the upstream of `y`.

**Comment by delta2323** [comment]
One more comment. In v2, which will be released in 30th May, we remove `volatile` option from `Variable`. Instead, the construction of computational graph is configured by the global variable `chainer.configuration.config.enable_backprop`. So, we will write as follow to do what we did in the previous comment:
```
with chainer.configuration.using_config('enable_backprop', False):
    x = Variable(np.array(...), volatile='off')
    y = f(x)
with chainer.configuration.using_config('enable_backprop', True):
    z = Variable(np.array(...), volatile='off')
    w = g(y, z)
w.grad = np.ones_like(w.data)  # can be omitted is w.data is scalar
w.backprop()
```

**Comment by sharpstill** [comment]
@delta2323 why delete volatile attribute from Variable? 
Isn't it too lengthy code if I write 5 Variable, each have different volatile attribute ?

**Comment by muupan** [comment]
Is this what you want?
```
l = Variable(np.array([3,0],dtype=np.float32))
c = np.array([2,1],dtype=np.float32)
import chainer.functions as F
F.sum(c+l)
```
If `c` is already a `Variable`, you can also write `F.sum(c.data+l)` to stop gradient flow through c.
