### ISSUE TITLE
Hope to supply more English language tech notes/material rather than Japanese

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#2869]
I currently Google how to fine tuning using pretrained model. I only googled a lot of blog written in Japanese. Just like this: 
http://qiita.com/ysasaki6023/items/3040fe3896fe1ed844c3
We foreigner also want to use this excellent framework but the Japanese language tech material limits many foreigner  to use.

**Comment by beam2d** [comment]
Thank you for giving a request! We have noticed that problem, but it is difficult for us developers to directly solve it.

We ourselves will work on improving the official documentation so that most of such questions will be covered. It does not directly solve the current problem of "too many Japanese articles", but I hope it would be helpful for users that cannot read these articles.

We might have to think about how to solve the original problem as well. Does anyone have any ideas?

**Comment by MannyKayy** [comment]
Having an English version of the [chainer playground](https://play.chainer.org/book) would be a good start.
The rest relies on the English speaking users to help write tutorials and articles for each other. It would be good to have a few ipython notebooks for standard tasks.

Additionally, i occasionally run into a blog post or ipython tutorial for chainer written in English . It would probably be useful to have a wiki that links to all the good tutorials.

**Comment by sharpstill** [comment]
@MannyKayy unfortunately, You mentioned https://play.chainer.org/ is also Japanese language blog
