### ISSUE TITLE
Cannot switch thread local variables function-wise during backward propagation

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#2938]
We cannot switch thread local variables on a granularity of Chainer functions, that could be problematic in some situation.

For example, we can temporarily enable/disable cuDNN by switching the value of `chainer.config.use_cudnn` (e.g. with `using_config('use_cudnn', False)`). But in backward propagation, we cannot disable it only a part of functions in a computational graph. 

Let's consider the following chain:

```
class Model(Chain):

    def __init__(self):
        with init_scope():
            self.l1 = L.Convolution2D(...)
            self.l2 = L.Convolution2D(...)
            self.l3 = L.Convolution2D(...)
```

We can disable cuDNN only in the second convolution as follows:

```
    def __call__(self, x):
        h = self.l1(x)
        with using_config('using_cudnn', False):
            h = self.l2(h)
        return self.l3(h)
```

But as all backward propagation of Chainer functions are embedded in `Variable.backward`, we cannot switch it without editing the library code.

This problem is reported by aoikaneko in the Japanese user forum. Thank you!

**Comment by kmaehashi** [comment]
I summarized the offline discussion:

* Currently some functions are preserving cuDNN status (whether cuDNN was used) in forward path as an attribute of the node. This is because cuDNN backward in such functions expects the input to be retained in the forward path.
  e.g., https://github.com/chainer/chainer/blob/v4.0.0b3/chainer/functions/activation/relu.py#L31-L47
* Use of iDeep is also determined by the thread-local configuration, so there is a same issue as cuDNN.
* After the discussion, it may be insufficient to just keep boolean flag, as the backward of the FunctionNode may be implemented with another FunctionNode call.  In such case we need to keep the config value (e.g., `never`) used in the forward stage instead of a boolean flag, and use that config in the backward path.
* Framework-level solution (e.g., preserve all configuration values in forward and restore it in backward, by inserting code around function hook invocation) sounds possible, but we need to consider the overhead this change will introduce.
* We should also discuss what config should be kept from forward to backward. (e.g., is it OK to run backward with `debug` config value used in forward?)

**Comment by delta2323** [comment]
Any update on this issue?
