### ISSUE TITLE
Pick an objective list of features for Chainer comparison

### ISSUE THREAD

**Issue by fchollet** [chainer/chainer#299]
Comparing Chainer with other libraries based on the things that Chainer supports (and that others don't) instead of an objective list of useful features, is simply bad faith. 

You should ask neutral 3rd parties (researchers in industry and academia) what features they are looking for in a library, and what applications they are implementing. Then aggregate the most commonly mentioned features / applications. Only with such features can you draw an objective comparison between different deep learning libraries. 

Likewise, if you do your benchmarks by selecting yourself which tasks to benchmark based on how Chainer does, then that is egregious bad faith. Hopefully you don't do that.

Very disappointed in Chainer for releasing such a misleading PR piece.

**Comment by cemoody** [comment]
François's suggestion of collecting more feedback from other parties is a good one. However, I don't really ascribe malice to this comparison table. I'll add one datapoint that Andre Karpathy talked about long ago in his post [The Unreasonable Effectiveness of Recurrent Neural Networks](http://karpathy.github.io/2015/05/21/rnn-effectiveness/). He devotes a section of his post to features he'd like to see:

> 1. CPU/GPU transparent Tensor library with a lot of functionality (slicing, array/matrix operations, etc. )
> 2. An entirely separate code base in a scripting language (ideally Python) that operates over Tensors and implements all Deep Learning stuff (forward/backward, computation graphs, etc)
> 3. It should be possible to easily share pretrained models (Caffe does this well, others don't), and crucially
> 4. NO compilation step (or at least not as currently done in Theano). The trend in Deep Learning is towards larger, more complex networks that are are time-unrolled in complex graphs. It is critical that these do not compile for a long time or development time greatly suffers. Second, by compiling one gives up interpretability and the ability to log/debug effectively. If there is an option to compile the graph once it has been developed for efficiency in prod that's fine.

**Comment by beam2d** [comment]
First of all, the table that we released is the first step to provide information for selecting candidate frameworks to implement one's own algorithms. We want to make the table more informative through the future development on GitHub, so any requests of updates and PRs are welcome.

The first version we released yesterday is incomplete since our survey cannot be perfect. It might have errors, though they should be fixed by the community as well as bugs in the implementation. One PR has already been posted and merged (#296). We appreciate such works.

The rows we picked up are based on what we are mainly focusing on, i.e., what we think important. In order to make the table more informative for possible users, what they really concern should be added in the future. We currently does not know what they are, though, so such updates are also done by the future development based on users' requests and PRs.

By the way, the table is hosted by the first party, which cannot be perfectly fair by nature. It is ideal that some neutral third party makes a survey and creates a comparison table, but we currently does not find such third party. At this moment, only what we can do is to make our table as fair as possible based on users' demand.

@cemoody Thank you for sharing the blog post! I've read it at some time but forgot it.
