### ISSUE TITLE
StandardUpdater should call Optimizer.new_epoch appropriately

### ISSUE THREAD

**Issue by grafi-tt** [chainer/chainer#3044]
I noticed that StandardUpdater doesn't call Optimizer.new_epoch.
So if you use an optimizer with StandardUpdater and Trainer, optimizer never knows what epoch is going on.

Fixing the issue is simple: just add
```python
if self.is_new_epoch:
    optimizer.new_epoch()
```
[here](https://github.com/chainer/chainer/blob/master/chainer/training/updater.py#L200).

Questions are

1. Is this behavior is intended?
2. If so, is it for compatibility?
3. If not intended, how do you think about changing this behavior, which breaks compatibility?

Thanks,

**Comment by beam2d** [comment]
Hi, sorry for the late reply. The original intention of `new_epoch` is that users should call it manually (e.g. by customizing the updater) if the epoch count is needed by the optimizer, but, as you pointed out, it definitely looks better to let the updater call it automatically. I think it's difficult to change this behavior due to the backward compatibility, but it is feasible to add a flag to `StandardUpdater` and let the updater call `new_epoch` automatically only when the flag is turned on by users.
