### ISSUE TITLE
Have somthing confused in gradient check

### ISSUE THREAD

**Issue by GeorgieJi** [chainer/chainer#3046]
Recently, I attempted to modify tree-lstm. After I finished my modification about it, I ran a gradient check in input size 5, it's OK. But, when I increased the dimension to 20, the gradient check fail, the value of error is increased, approximate, to e-2. Then I try to change the type of input from float32 to float64, the situation still exist, but it occurs error after I increased the input size to 30, not 20 . I sincerely need your help about it. Thanks.

**Comment by unnonouno** [comment]
I feel your implementation is correct.

`gradient_check` calculates gradients using numerical differentiation.
https://en.wikipedia.org/wiki/Numerical_differentiation
It calculates numerical difference `(f(x + e) - f(x - e)) / 2e` for small `e` using `forward` method for each dimension and compares it with result of `backward` method.
Numerical differentiation has numerical error. Especially when you use small floating point types such as float32 and float16, it easily causes such error because difference of `f(x+e)` and `f(x-e)` is too small to represent in such types of floating point.
Gradient check calculates numerical difference for all dimension. So when you use larger dimension of arrays, its errors are summed up and it becomes larger. You don't need to use large size of arrays for check.

**Comment by GeorgieJi** [comment]
Thanks for your immediate support and proof . So, based on your elaboration, I guess the issue maybe is caused by the model I modified itself. I'll take another attempt on it. Thanks sincerely.
