### ISSUE TITLE
feature request: there is no way to using pretrained .npz model but modified some layer

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3131]
I have ask this question in stackoverflow
https://stackoverflow.com/questions/45589028/how-to-load-pretrained-chainer-npz-parameter-file-but-modify-some-layer
but I found there is no way to do this. When I do this as his proposal.
I found chainer report error:
ValueError: numpy and cupy must not be used together type(W): <class 'numpy.ndarray'>, 
type(x): <class 'cupy.core.core.ndarray'>

**Comment by delta2323** [comment]
Thank you for your question. As wrote [in this reply](https://stackoverflow.com/questions/45589028/how-to-load-pretrained-chainer-npz-parameter-file-but-modify-some-layer#comment78171231_45590028), I guess the problem is the inconsistency between model parameters and input arrays in which they are allocated. Could you try `to_gpu` method?
