### ISSUE TITLE
Poor performance in example - train_sentiment.py- with gpu version

### ISSUE THREAD

**Issue by GeorgieJi** [chainer/chainer#3168]
Hi, 
   I'm confused about the poor performance, especially the coefficient of utilization, when I'm running example train_sentiment.py with gpu version in the official github website. 
![image](https://user-images.githubusercontent.com/23255184/29402648-4f9c2e16-8368-11e7-8bcd-fb57f43162b2.png)
   The coefficient of utilization is below 10%, but I'm sure that the gpu is working. When I try another example, like mnist, the coefficient is almost 100%.
   What's wrong with it? Thanks for your help.

**Comment by unnonouno** [comment]
Yes, "sentiment" is very slow even with GPUs. This is an example of recursive neural networks (tree-rnn) and it is hard to make mini-batch for recursive neural networks. Actually in this example, batch size is always one.
BTW, I made a mini-batch training for recursive networks in https://github.com/chainer/chainer/pull/2135. It is very faster than the original.

**Comment by GeorgieJi** [comment]
Thanks, I found the ThinStackRecursiveNet version as you say. I'll try it later, cause it's required to install the chainer in that special version. Because my work is totally built based on that example code, and it will take much time to transform into thinstakckRN version, is it possible for you to tell me the root of the poor power in "sentiment"?  The batch size I used is 25.

**Comment by unnonouno** [comment]
Sorry for late reply.
Oh, really? The main reason that TreeRNN (recursive neural networks) is slow is that we cannot make mini-batch because tree structures are different with each other. So, in the original example we does not make a mini-batch and instead uses only one example for each update. In this case, GPU is slower than CPU.
Thin-stack version uses stack operation instead of tree structure. I mean we can convert any tree structures to corresponding stack operations. Stack operations is a sequence of operations. So we can make a mini-batch in such case and it can be calculated with GPUs efficiently.

**Comment by GeorgieJi** [comment]
Thanks for your reply and all your support. I have implemented the Thin-stack, it's so cool - dramatically fast. And tracking your code, I agree with your answer about the reason why the normal rnn is slow.
