### ISSUE TITLE
Behavior of extract() in ResNet and VGG models is different in v1 and v2

### ISSUE THREAD

**Issue by rezoo** [chainer/chainer#3210]
In chainer v1, it was assumed that `extract()` methods in ``ResNetLayers`` and ``VGG16Layers`` extract feature vectors in *test* mode.
```python
import chainer.links as L
model = L.ResNet50Layers()
feature = mode.extract([image])  # it is equivalent to extract([image], test=True)
```

However, in v2 we have to explicitly use ``with chainer.use_config()`` clause like that:
```python
with chainer.use_config('train', False):
    feature = mode.extract([image])
```
This specification is a bit confusing; users might expect that ``extract()`` literally extracts feature vectors regardless of the training mode, but it is not correct. Although I do not think that it is right thing to change this specification from now on, it would be better to add the above description to the comment.

**Comment by delta2323** [comment]
The other solution would be to turn off `train` mode  in `extract` method forcibly. Do you think it restricts the usage of the method?

**Comment by delta2323** [comment]
bump

**Comment by kmaehashi** [comment]
If we are to fix this, we should include this in v4 release, as this is obviously no-compat.

**Comment by delta2323** [comment]
I discussed this issue with @rezoo and want to propose the following changes:
- Write explicitly in the document of `extract` that the default value of `train` has been changed from v2.
- Check the value of `chainer.config.train` in `extract` and raise an warning when it is `True` possibly in debug mode. (This might be inappropriate because we do want to set it to `True` in some case (e.g. test-time dropout).

@kmaehashi  @rezoo How do you think of the proposal?
