### ISSUE TITLE
Defer initialization of size of BatchNormalization and infer it at first iteration.

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#3221]
The input dimension of several links (e.g. `L.Linear`, `L.Convolution`) do not have to be fed and is inferred by the minibatch size of the first iteration. Theoretically we should do the similar thing with `L.BatchNormalization`.

**Comment by tkanmae** [comment]
Hi, I started working on this issue. To implement this lazy inference,`BatchNormalization` needs to know an axis or axes of channel dimension(s) in an input tensor, instead of a size or a shape of input channels. [My work-in-progress implementation](https://github.com/tkanmae/chainer/tree/infer-input-size-in-batchnorm) has `BatchNormalization` with a constructor like

``` python
def __init__(self, axis=1, decay=0.9, eps=2e-5, ...):
``` 
where `axis` is an int or a tuple of ints that specifies an axis or axes of channel dimension(s) in an input tensor. The default value of `1` assumes that a mini-batch size is at the first dimension, channels is at the second dimension and the rest is the spatial dimensions of a sample.

But this will break compatibility with existing code. 

Is there any better approach to implement this feature? What do you think?

**Comment by delta2323** [comment]
Thank you for your interest! I would suggest that the improved implementation should accommodate the original usages. If users assume the original API use this API, the function wrongly interpret the first argument as `axis`. 

Similar problem occurred when we introduce input size inference of `L.Linear`. So its implementation could be helpful.

One idea I come up with is to apply two-step change.
1. Add `None` to the types that `size` accept and add `axis` argument. If size is `None`, `axis` is used to infer the channel dimension(s).
2. Allow users to remove the first argument. If the first argument is removed, users have to specify non-default options as keyword arguments (See [the document of `L.Linear`](https://github.com/chainer/chainer/blob/master/chainer/links/connection/linear.py#L74)).

**Comment by tkanmae** [comment]
Thanks for the feedback. I will continue working on it.

**Comment by delta2323** [comment]
Hi. Can you spare time to continue to work on this? If it is difficult, we may take over your work. thank you.

**Comment by tkanmae** [comment]
Sorry, I've forgot this, but I'm still willing to work on it.  Can you give me a few days to see how far I can go?  If you have a coming deadline and have little time, I'm happy to hand this over to you.

**Comment by delta2323** [comment]
Thank you for your reply. We do not have any special deadline. I would happy if you work on it.

**Comment by delta2323** [comment]
Hi, how are you?

**Comment by tkanmae** [comment]
Thanks for reminding me. I just made a pull request (#4149) addressing this issue.

**Comment by delta2323** [comment]
Thank you!

**Comment by delta2323** [comment]
We are now working on this issue in PRs #4266 and #4149.
