### ISSUE TITLE
Automatic cupy conversion

### ISSUE THREAD

**Issue by Crissman** [chainer/chainer#3266]
In general, Chainer is able to move calculations to the GPU and use CuPy automatically if `device=0` or greater, but errors can still be encountered at inference time and other stages if `.to_gpu()` is not used to move numpy arrays over to the GPU. This produces this kind of error:

```Traceback (most recent call last):
  File "shrooms.py", line 129, in <module>
    predict = model.predictor(x[None]).data
  File "shrooms.py", line 75, in __call__
    h1 = F.relu(self.l1(x))
  File "/usr/local/lib/python3.4/dist-packages/chainer/links/connection/linear.py", line 127, in __call__
    return linear.linear(x, self.W, self.b)
  File "/usr/local/lib/python3.4/dist-packages/chainer/functions/connection/linear.py", line 107, in linear
    return LinearFunction()(x, W, b)
  File "/usr/local/lib/python3.4/dist-packages/chainer/function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python3.4/dist-packages/chainer/functions/connection/linear.py", line 40, in forward
    .format(type(W), type(x)))
ValueError: numpy and cupy must not be used together
type(W): <class 'cupy.core.core.ndarray'>, type(x): <class 'numpy.ndarray'>
```

In this case, it would be preferable if instead of exiting with an error, Chainer automatically converted the numpy array to a cupy array.

Is this a feasible enhancement?

**Comment by beam2d** [comment]
Thank you for the proposal. The current design policy around the array locations is that data transfer should be done explicitly so that users and developers can be fully aware of where the data transfer happens. At least for now, we should not just let numpy ndarray automatically be converted to cupy ndarray (otherwise one may easily mix up devices and cause severe performance degradation which is hard to fix).

I also understand that it is sometimes cumbersome, but I have not found any good solutions on this matter. Adding a flag to change this behavior might be one solution, but I'm not sure if it is actually convenient. Another solution is to introduce the concept of "current device", to which every array on different devices would be automatically transferred when needed.

**Comment by Crissman** [comment]
Closing this issue, since silent automatic conversion will not be supported.
