### ISSUE TITLE
Stop backprop when all gradients are None

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#3435]
We need to stop backprop if all gradient variables are None.
```
(chainer.Variable(numpy.array([1, 2], 'f')) * 1).backward()
```
It causes TypeError:
```
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

**Comment by beam2d** [comment]
I think it should raise an error anyway, though the error message should also be more informative. What do you think?

**Comment by unnonouno** [comment]
I also think it is better to modify the error message.

**Comment by toslunar** [comment]
I tried to fix the issue.

First try:
```
        # Initialize error by 1, if this is a loss variable
        if self._grad_var is None:
            if self.data.size != 1:
                raise RuntimeError('Cannot backward non-scalar variable'
                                   ' without explicit grad')
```
Some tests failed. I realized non-differentiable functions don't read the grad of y.

Second try:
```
        if self._grad_var is None:
            if self.data.size != 1:
                with cuda.get_device_from_array(self.data) as device:
                    if device is cuda.DummyDevice:
                        self.grad = numpy.full_like(self.data, numpy.nan)
                    else:
                        self.grad = cuda.cupy.full_like(self.data, numpy.nan)
            else:
                with cuda.get_device_from_array(self.data) as device:
                    if device is cuda.DummyDevice:
                        self.grad = numpy.ones_like(self.data)
                    else:
                        self.grad = cuda.cupy.ones_like(self.data)
```
Some tests failed. Really? It seems None is backward-ed somewhere in order to backward zero.

The following change passes the non-slow cpu tests
```
        if self._grad_var is None:
            if self.data.size != 1:
                with cuda.get_device_from_array(self.data) as device:
                    if device is cuda.DummyDevice:
                        self.grad = numpy.zeros_like(self.data)
                    else:
                        self.grad = cuda.cupy.zeros_like(self.data)
            else:
```

**Comment by toslunar** [comment]
My second try `self.grad = xp.full_like(self.data, numpy.nan)` passes the test if #4015 is merged.

**Comment by Crissman** [comment]
@toslunar #4015 has been merged. Can you make a PR for this?

**Comment by toslunar** [comment]
> We need to stop backprop if all gradient variables are None.

Be careful with the meaning of "all". Recall:
1. `v.backward()` may gather gradients from variables other than `v`;
2. a function node may have multiple outputs.

The condition "all the output nodes **of a function node** `f` are `None`" does not imply we can ignore `f` (i.e. `continue` the loop) in `Variable.backward()`. For example, consider:
```
>>> x = chainer.Variable(np.arange(6).reshape(3, 2).astype('f'))
>>> y0, h = chainer.functions.split_axis(x, [1], axis=0)
>>> y0
variable([[0., 1.]])
>>> y1, y2 = chainer.functions.split_axis(h, [1], axis=0)
>>> y1
variable([[2., 3.]])
>>> y2
variable([[4., 5.]])
>>> y0.grad = np.array([[1, 1]], 'f')
>>> y2.backward()
>>> x.grad
array([[1., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)
```

I agree that the fact 1. is a kind of a pitfall, or it could be a bug.
```
>>> x = chainer.Variable(np.arange(8).reshape(4, 2).astype('f'))
>>> h, k = chainer.functions.split_axis(x, [2], axis=0)
>>> y0, y1 = chainer.functions.split_axis(h, [1], axis=0)
>>> y2, y3 = chainer.functions.split_axis(k, [1], axis=0)
>>> y0.grad = np.array([[1, 1]], 'f')
>>> y3.backward()
>>> x.grad
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)
>>> h.grad = np.array([[1, 1], [1, 1]], 'f')
>>> y3.backward()
>>> x.grad
array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)
```

**Comment by toslunar** [comment]
#6260

**Comment by toslunar** [comment]
See also #7910.

**Comment by niboshi** [comment]
There are some choices about `Variable.backward()` from a variable whose shape != `()` and gradient not set.
1. Forbid it (as in the PR #7928).
2. Just do nothing
3. Treat as if 1 is set as the gradient (how `chainerx.ndarray.backward()` currently works).

I think 2. is the most consistent, as `grad = None` is a synonym to `grad = zero` in most cases.

For example, the following code fragment will only work in 2.
```py
...
y2.grad = x1.grad   # x1.grad is calculated before in some way
y2.backward()
```

**Comment by beam2d** [comment]
I agree that option 2 is the most consistent, but then it could be difficult to debug when the user just forgot setting output grad. What do you think about this point?

**Comment by niboshi** [comment]
In order to avoid that, there could be another option:

4. Flag on a variable whether `.grad` is manually set. If no grad is set, raise an error. If `None` is set, just do nothing.

  `Variable` already has `._grad_valid` flag. Currently it can be `False` only in `Parameter`.
We could set it to `False` by default for variables created as outputs of `FunctionNode.apply()`.

**Comment by beam2d** [comment]
That sounds good for avoiding my concern. I like the idea of making `.grad` invalid until setting or initializing it. We should be careful on the compatibility break it introduces, though: it will be invalid to get `.grad` before setting any value (it is currently allowed, returning `None`). I'm not sure how much it affects user code.

We may want to expose the `grad_invalid` flag or making `.grad` return a special value like `UNINIT` instead of raising an error for uninitialized grad, to write e.g. code like below.

```py3
if output.grad_valid:
    output.grad = None
output.backward()
```

**Comment by beam2d** [comment]
We should also consider carefully the case of zero-dimensional output. There are three cases:

- `.grad` is invalid
- `.grad` is a (zero-dimensional) array
- `.grad` is `None`

The first two cases may be treated as the current one. The third case would be worth reconsidering the behavior. If we take consistency, it will "do nothing". If we take compatibility, it will behave like the first case. I would like to take compatibility for this case because it could affect much more existing user code.

**Comment by niboshi** [comment]
One concern of that specification is

>```py
>...
>y2.grad = x1.grad   # x1.grad is calculated before in some way
>y2.backward()
>```

This code would result in an incorrect value *silently*, for 0-d variables...
