### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by libebc** [chainer/chainer#3483]
Hi,
There are some errors when I run the sample code from others.
I guess that the sample code used the older version of chainer.
Can you give me some advices? Thank you!
Following are the error messages and the condition of my machine.

* Error messages, stack traces, or logs

```
File "/usr/local/lib/python2.7/dist-packages/chainer/functions/noise/dropout.py", line 68, in dropout
    kwargs, train='train argument is not supported anymore. '
File "/usr/local/lib/python2.7/dist-packages/chainer/utils/argument.py", line 4, in check_unexpected_kwargs
    raise ValueError(message)
ValueError: train argument is not supported anymore. Use chainer.using_config
```

* Conditions
  - Chainer version: 2.1.0
  - CuPy version: 1.0.3
  - OS/Platform: Ubuntu 16.04.3
  - CUDA version: 8.0.61

**Comment by niboshi** [comment]
Thank you for posting!
There is a [relevant section](https://docs.chainer.org/en/stable/upgrade.html#global-configurations) in the official upgrade guide. Please refer to it.

Also, we recommend posting questions (other than bug reports and feature suggestions) to [StackOverflow](https://www.stackoverflow.com) with `chainer` tag, so that this kind of knowledges will be more exposed to wider range of users.
Please consider it next time :)
