### ISSUE TITLE
 Enable sphinx nitpicky mode to detect dead references

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3686]
Sphinx documentation: http://www.sphinx-doc.org/en/stable/config.html#confval-nitpicky

(See https://github.com/cupy/cupy/issues/657 for the corresponding issue in CuPy)

**Comment by kmaehashi** [comment]
I tried this option, however, it raises error for all references that is not included in autosummary.

For example, the line 10,

```
:mod:`chainer.utils.type_check`
```

is an error, because it is not listed in `autosummary` (thus, there is no doc for the module.)

https://github.com/chainer/chainer/blame/v3.0.0/docs/source/reference/check.rst#L10-L21
https://docs.chainer.org/en/v3.0.0/reference/check.html

**Comment by niboshi** [comment]
How about using `.. currentmodule::` directive explicitly?

**Comment by kmaehashi** [comment]
Maybe we can filter the errors in nitpicky mode by checking if the attribute in error exists in runtime. I'll try.

**Comment by niboshi** [comment]
bump
