### ISSUE TITLE
Serialize random states in iterators for better reproducibility

### ISSUE THREAD

**Issue by takagi** [chainer/chainer#3754]
Iterator implementations generate new order with `numpy.random` when they come across the end of a dataset and repeat over it.

However they currently do not serialize the random state but the new order after they repeat cannot be reproduced across resume/suspend.

Managing and serializing the random state in iterators will give us better reproducibility on that situation.

See #3575 .

**Comment by grafi-tt** [comment]
@takagi Sorry for late reply! I agree with you, this would be useful feature. 

I have been reluctant to work on the feature because of the amount of work. It isn't very large work, but at least it should be implemented on `SerialIterator` as well as `MultiprocessIterator` in backward compatible manner with test codes, and some document update is very desirable.

Now I'm feeling I can spare time to the issue. Hopefully I'll send a PR until the mid January.

**Comment by grafi-tt** [comment]
Serialization order sampler required. Related: #5042

**Comment by grafi-tt** [comment]
bump

**Comment by grafi-tt** [comment]
bump
