### ISSUE TITLE
ImageNet example lacks necessary steps to run

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#3892]
The current `imagenet` example lacks how to prepare the dataset to pass to the scripts. It is based on Caffe's dataset format, though nowadays I don't think it is reasonable to assume the experience on Caffe for new users. This information is definitely needed to let ImageNet newbies easily try large-scale visual classification with Chainer.

**Comment by dokutagero** [comment]
Could you give me some hints about what would be interesting to cover in a simple example? I'm currently learning Chainer (I'm new to it) so I could try to make an example.

**Comment by beam2d** [comment]
Are you talking about adding a new example and not about `imagenet`, which is the main topic of this issue?

**Comment by dokutagero** [comment]
Sorry, I'm not sure if I understood properly the topic of the issue. I was talking about preparing some code to run  models from `imagenet`, preparing the dataset, optimizer, trainer, etc

**Comment by beam2d** [comment]
Ah, ok, my explanation was not clear. This issue aims at how to run the `imagenet` example itself. It lacks how to prepare the training and validation datasets to feed to `train_imagenet.py`. Sorry for confusion.

**Comment by saqibns** [comment]
Hi. I'd love to contribute but I'm new to chainer and deep learning.

**Comment by mitmul** [comment]
I'll fix this issue by changing the example itself to use the ImageNet-1K dataset hosted by Kaggle.

**Comment by mitmul** [comment]
Bump

**Comment by crcrpar** [comment]
It will lack backward compatibility, but it would be more user-friendly if `L.Classifier` is used in training because :meth:`forward` of models in current examples/imagenet take (x, t) as input and return loss.

This way of implementing is easier to train but it sometimes bothers users when it comes to inference.
Users would assume one model takes x as its input and returns prediction (label or some value) as its output.

So, in my opinion, models should implement forward method in a way that they take x as their input and return prediction.
In training, before setting up an optimizer, we wrap a model by `L.Classifier`. 
In this case, the big picture of `train_imagenet.py` would look like the below snippet.

```python
class MyModel(chainer.Chain):
    ...
    def forward(self, x):
        ...
        return y

...

model = L.Classifier(MyModel(...))
optimizer = SomeOptimizer(...)
optimizer.setup(model)

...
```

**Comment by beam2d** [comment]
Bump

**Comment by niboshi** [comment]
@mitmul Do you have any progress?
