### ISSUE TITLE
A concern about deprecating link-adding interfaces except init_scope

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#4106]
From Chainer v2, `init_scope` is introduced as a new interface to add parameters and child links. While I think this interface is nice in a sense that it helps IDEs and users understand they can be used as attributes, I have a concern about deprecating the old interfaces: `Chain.__call__` and `add_link`.

Let's say I want to wrap two links to make a single link.
Old interface:
```
chain = chainer.Chain(a=LinkA(), b=LinkB())
```

New interface:
```
chain = chainer.Chain()
with chain.init_scope():
    chain.a = LinkA()
    chain.b = LinkB()
```
It's lengthy and unnecessarily stateful.

Another example is to construct a Chain when child links and names are determined at runtime. I guess in this situation IDEs cannot infer attributes anyway.
Old interface:
```
chain = chainer.Chain(**children)  # children is a dict holding child links by their names
# or
chain = chainer.Chain()
for name, link in children:
    chain.add_link(name, link)
```

New interface:
```
chain = chainer.Chain()
with chain.init_scope():
    for name, link in children:
        setattr(chain, name, link)
```
I feel `setattr` is less readable to humans than `add_link`.

I guess Chain is mainly designed to be used via inheritance, not by direct instantiation, but defining a new class for just wrapping other links seems overkill to me. I want it to work as a container as well.

I don't mean Chainer should stop deprecating the old interfaces, as I guess the developer team already had discussions on it. I just want to show my concern and hear opinions on it from other users as well as from the developer team.

**Comment by niboshi** [comment]
Recently I have been thinking about the same thing (on `add_link` vs `setattr`) and actually about to raise an issue.
`setattr` is not only less readable but also cannot detect unintended value type.
I'm +1 for reviving it.

Same for `Link.add_param`, but with single `Parameter` argument (we can still preserve compatibility).

**Comment by beam2d** [comment]
When we discussed deprecating the old interface, we did not consider the container-style usage (and only considered the OOP-style one). I understand it turns out that sometimes OOP style model definition is overkill (or simply does not fit to the model design well) where the container-style definition is more natural, so it makes sense to reconsider the old interface. We should be aware of the difference in recommended situations to use either of them and it should be clearly noted in the documentation.

One note on un-deprecating the interface: I think `Chain.__init__` should be improved so that it also accepts parameters to register (like `setattr` inside `init_scope` does) so that users do not have to use `Link` and `Chain` differently (I think most users will then just use `Chain`, which is simple and easier to understand).
