### ISSUE TITLE
No contribution guide for "× Jenkins -- Build finished"

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#4130]
Contributor guide says
> After the automatic test passes, some of the core developers will start reviewing your code.

A contributor, however, might not proceed without help of a core developer.
<img width="781" alt="screen shot 2017-12-21 at 12 31 01" src="https://user-images.githubusercontent.com/1964281/34239639-049d8d46-e64c-11e7-9cd9-7e3a8ff65e24.png">

**Comment by kmaehashi** [comment]
Thank you for raising an issue.
Actually exposing "× Jenkins -- Build finished" message is not what we want (this is due to a bug of Jenkins plugin; https://github.com/jenkinsci/ghprb-plugin/issues/551).
I read the plugin source code and reconfigured Jenkins to try to workaround the bug, and I believe this message will not be displayed for future PRs.

**Comment by toslunar** [comment]
Thanks a lot!

**Comment by kmaehashi** [comment]
I confirmed that the workaround is actually working.

**Comment by MaciejCiach** [comment]
@kmaehashi Can you share your workaround ?

**Comment by kmaehashi** [comment]
@MaciejCiach I shared the workaround in the original issue.
