### ISSUE TITLE
Gradients are not kept in intermediate unreferenced variables even when Variable.backward() is called with `retain_grad=True`

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#4220]
Target Chainer version: v3.3.0, v4.0.0b3

According to the document of [`Variable.backward`](file:///Users/oonokenta/dev/chainer2/docs/build/html/reference/core/generated/chainer.Variable.html#chainer.Variable.backward), gradients of intermediate variables should be kept when `retain_grad` option is `True`. But they are not in some case: 

```python
import chainer
import chainer.functions as F
import numpy as np

print(chainer.__version__)
x = chainer.Variable(np.ones((5, 5), np.float32))
y = x + 1  # (1)
# (2)
y = F.sum(y)
y.backward(retain_grad=True)
target = y.creator.inputs[0]  # Note that target is VariableNode, not Variable.

assert target.get_variable_or_none() is None
assert target.grad is None
assert float(x.grad.sum()) == 25.0  # Gradient of the input variable is computed correctly.
```

I guess it is because `Variable` made in the line (1) is not referenced any more when `backward` is called and is freed. Actually when we insert `z = y` in (2), the first assertion is violated. Note that [`Variable.creator`](https://github.com/chainer/chainer/blob/master/chainer/variable.py#L175) and [`FunctionNode.inputs`](https://github.com/chainer/chainer/blob/master/chainer/function_node.py#L108) have documents, although it is not registered in RTD. Therefore, it seems to me `y.creator.inputs[0]` should be considered as a valid operation.

**Comment by delta2323** [comment]
bump

**Comment by belltailjp** [comment]
Hi! I also had a situation where I want to get grads of an intermediate Variable(Node) from a computational graph.
Ideally I do think we should modify or extend the network implementation so that we can get activations (intermediate `Variable`) like what chainer's ImageNets and chainercv's `PickableSequentialChain` do.
In case I don't want to modify the code of the network (e.g. it's from pip-installed library or very complicated implementation etc), that could be infeasible.


> I feel we should explicitly note how to retrieve the retained gradients after calling backward(retain_grad=True).

Does this mean that the gradients are actually kept somewhere regardless of Variables' lifetime, although currently the document just doesn't explain how to do that?
