### ISSUE TITLE
AttributeError: 'Adam' object has no attribute 'zero_grads'

### ISSUE THREAD

**Issue by TamouzeAssi** [chainer/chainer#4708]
Im using a code not writing by me. So when executing this code we get error about the inexistance of zero_grads()
```
optimizer.zero_grads()
AttributeError: 'Adam' object has no attribute 'zero_grads'
```

This code is:

import chainer.optimizers as O
optimizer = O.Adam()
optimizer.setup(model)
clip = chainer.optimizer.GradientClipping(5.0)
optimizer.add_hook(clip)
....

optimizer.zero_grads()
Does i should change: optimizer.zero_grads() to

optimizer.use_cleargrads(use=True)?
Note that im using chainer 4.0 version and the code what building with chainer 1.5.

**Comment by abhayraw1** [comment]
I guess instead of passing `True` for `use` argument  you'll have to pass False:

`optimizer.use_cleargrads(use=False)`
you can have a look at the function definition [here](https://github.com/chainer/chainer/blob/bc3516b07adc5e98b52307431b7e1aa149f16290/chainer/optimizer.py#L660) which resides in the base class of [Adam](https://github.com/chainer/chainer/blob/v4.0.0/chainer/optimizers/adam.py)

Hope it helps.

**Comment by crcrpar** [comment]
If you want to just clear/zero out gradients of model by `optimizer.zero_grads()` and explicitly call `loss.backward()` in your code, `model.cleargrads()` would be used instead of `optimizer.zero_grads()`.

This document might help you. https://docs.chainer.org/en/stable/examples/train_loop.html#write-a-training-loop

**Comment by kmaehashi** [comment]
See also the upgrade guide, which helps you migrating from older Chainer code. https://docs.chainer.org/en/latest/upgrade.html

**Comment by kmaehashi** [comment]
Feel free to reopen the issue if you still have any trouble. Thanks again for the feedback!

**Comment by hasan-moni-321** [comment]
Please, don't mix Keras optimizer and Torch Optimizer. 

If you use Tensorflow, you should use Tensorflow optimizer
If you use PyTorch, you should use Torch optimizer

**Comment by yazidhadni** [comment]
For those like me that had the same issue and have landed here :  there is no `zero_grads()`, you should write `zero_grad()` instead.
