### ISSUE TITLE
check_type_forward in math operations

### ISSUE THREAD

**Issue by eulerreich** [chainer/chainer#486]
Most of the checks have a clause "in_types[0].shape == in_types[1].shape" forcing the arguments in, e.g. multiplication and division, to have the same shape. This completely blocks the broadcasting feature of numpy.

Is this intentional? I took out that clause and my code runs just fine.

**Comment by beam2d** [comment]
Thank you for pointing it out. This is because these functions do not support de-broadcasting on backward. For example, Add with broadcasting must accumulate gradient correctly on backward, which current implementation does not support.

There is also a design issue on the broadcasting interface. Implicit broadcasting like NumPy is easy but prone to embed a bug that raises an error at distant point (or at the worst case, no error with incorrect results), which is hard to debug. So, there is a chance to adopt explicit broadcasting (like Torch does). We should start from thinking about the design.

**Comment by eulerreich** [comment]
I see. So is there a broadcasting function implemented right now? I only
see `shape` in the docs, but I don't think that does broadcasting.

For the Add case, we can just compute the gradient for each copy of the
broadcasted array and then sum them up to get the gradient. This approach
should work for a lot of functions.

**Comment by beam2d** [comment]
No, we do not have a broadcasting function yet. See also #228 (no additional info, though).

**Comment by beam2d** [comment]
We now have `F.broadcast_to` to broadcast variables. We might discuss automatic broadcasting in the future, but here I close this issue for now.
