### ISSUE TITLE
Remove deprecation messages from Chainer Docs

### ISSUE THREAD

**Issue by Crissman** [chainer/chainer#5026]
As I read through the Chainer docs, many pages feel overly long due to the repeated deprecation and other warnings, often from v1 or v2 of Chainer. I feel this gets in the way of clean explanations, such as on this page: https://docs.chainer.org/en/stable/reference/generated/chainer.links.GRU.html

How about we remove the deprecations, instead displaying as code warnings or version release notes?

**Comment by kmaehashi** [comment]
I'm thinking about the same thing. How about cleaning up deprecations since v2 (or earlier) from docs in v5?
cc/ @beam2d @niboshi

In that case it's better to make sure that everything is covered in the Upgrade Guide.
e.g. https://docs.chainer.org/en/stable/upgrade_v2.html#the-interfaces-of-gru-and-lstm-are-aligned

It's also related to #3233: inherited methods (altogether with docs including deprecation warnings) are displayed in subclasses.

**Comment by beam2d** [comment]
+1 for removing documentation of methods deprecated for long time.

We have to be careful about issues related to un-deprecate some features of `Link` and `Chain` (#4106); these are deprecated since v2 but we are planning to make them non-deprecated again. We should not remove documents of these methods.

**Comment by Crissman** [comment]
Completed.
