### ISSUE TITLE
Support dataset with undetermined length

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#5048]
In some cases users may want to iterate over dataset with underermined length:

* Exclude bad data during iteration (#4460)
* Support streaming data source

Currently the framework expects that `len(dataset)` is available/consistent and `dataset` is slicable, which makes hard to support such dataset.

The simplest solution would be to create a wrapper dataset that iterate over every item of the underlying dataset at first to make a list of valid indices of the dataset, but it requires all elements to be loaded before starting the iteration.

**Comment by Crissman** [comment]
The streaming data source is important for RL.

**Comment by niboshi** [comment]
Instead of a new iterator, I think it's better to make `len(dataset)` optional in the iterator(s), because parallelism (serial/multithread/multiprocess) and whether to support streaming dataset are orthogonal.

I also think perhaps we should separate ordering features (shuffle/order_sample) from the existing iterators, because it's also orthogonal w.r.t. parallelism. If they're separated, each iterator implementation will be much simpler.

**Comment by niboshi** [comment]
We had a discussion today and lowered the priority as RL will be handled in a different way: not by datasets/iterators.
