### ISSUE TITLE
Feature request: setting number of iterators to prefetch in multithreaditerator

### ISSUE THREAD

**Issue by jnishi** [chainer/chainer#5153]
Though multithreadIterator supports prefetch, number of prefetch iterator is fixed to 1. Would you add features to support preetching multiple iterators like multiprocessiterator?

If It was supported, it would be useful to train with too large data to load to RAM, and training process would be faster by loading data to GPU in prefetching that cannot do by using the multiprocessiterator.

**Comment by grafi-tt** [comment]
@jnishi This design difference is not due to the fundamental difference between process and thread. It is just a matter of whether having a dedicated background prefetch thread or not, so porting this feature from `MultiprocessIterator` is not hard.

But this feature makes `MutlithreadIterator` complicated, because of the needs of communication between the background thread, `reset` support, correct termination, etc.

Though I had written the mechanism to support those for `MultiprocessIterator`, I don't have time and energy to adapt and port the mechanism to `MultithreadIterator`. Another concern is maintainance cost. I'm not a paid core developer of Chainer, I couldn't take responsibility of maintenance.

I'm glad if the task is done by someone. I personally would like to see the feature too, because I noticed `MultithreadIterator` can't fully utilize GPU on a benchmark I'm conducting. I'll settle to `MultiprocessIterator` with manually allocated shared memory, but this is awkward.

**Comment by grafi-tt** [comment]
Another possibility is a static prefetch without the background thread, which is implemented in `MultiprocessIterartor` of Chainer v.2.x. This is simple, but I guess it doesn't have substantially performance benefit. (Don't believe what I guess. I didn't conduct a benchmark.)

**Comment by jnishi** [comment]
I would appreciate it to consider this issue.
I understand that main issue  is not the porting cost but maintenance cost. I agree that it is important to maintain software. I'll consider another way.

Thanks again.
