### ISSUE TITLE
Support add_dot

### ISSUE THREAD

**Issue by bordingj** [chainer/chainer#522]
Currently, the following operation:

C += cp.dot(A,B)

performs 2 operations; dot and add, and it also allocates an array for the output for the dot operation which is not used anyway after the add. The underlying BLAS operations is an add_dot operation so the add operation should be redundant. I suggest to add an add_dot operation:

C = cp.add_dot(A, B, C)

similar to the one in scikit-cuda: https://scikit-cuda.readthedocs.org/en/latest/generated/skcuda.linalg.add_dot.html?highlight=add_dot#skcuda.linalg.add_dot

**Comment by tscohen** [comment]
Numpy doesn't support this directly, so I wouldn't put add_dot in the cp namespace. That would make it more difficult to write device-agnostic code. However, scipy wraps many BLAS routines: http://docs.scipy.org/doc/scipy/reference/linalg.blas.html

Perhaps we could have a cuSciPy namespace where we put these functions with their BLAS name?

**Comment by bordingj** [comment]
cupy.cuda.cublas already support similar wrappers as http://docs.scipy.org/doc/scipy/reference/linalg.blas.html, but I think it would be nice to have an add_dot function that does all the things cp.dot does.

Numpy doesnt support it because on the CPU almost all the time is spent in the BLAS routine anyway. But on the GPU a relative significant amount of time is spent allocating the unused output and doing the elementwise add afterwards, because cuBLAS is so fast. 

All the chainer functions that performs a dot operation with a parameter does an add dot in their backward method, so it might give chainer a significant speed up to support this.

**Comment by tscohen** [comment]
I completely agree that this is a useful feature. I just think we should keep cupy as close as possible to numpy, so that you can write device agnostic code (i.e. code that runs on both numpy or cupy) without running into all sorts of small incompatibilities.

Cupy.cuda.cublas is a very thin wrapper that does not know about cupy.ndarray. I think the nicest way to add the add_dot feature would be to mirror the scipy.linalg.blas API for cupy.ndarrays. Those functions are quite easy to use, and you could still write device-agnostic code.

Or is there some extra features that add_dot should have that none of these BLAS functions have?

**Comment by bordingj** [comment]
I thinking that add_dot should check shapes compatibility, flags, and select and call the appropriate cuBLAS routine dependent on the inputs.
