### ISSUE TITLE
CentOS 6.5 version

### ISSUE THREAD

**Issue by shubham-IISc** [chainer/chainer#5273]
Hello everyone
Does chainer works with CUDA enviroment for CentOS 6.5.
I keep on getting the following error in my trainign log file whenever I run with GPU support.
![w1](https://user-images.githubusercontent.com/35381101/44627702-e4be7e00-a94f-11e8-9383-4d526f45d4f8.png)

Following is the queue.pl error:
![w2](https://user-images.githubusercontent.com/35381101/44627709-17687680-a950-11e8-91cd-77b936b16664.png)

Could it be because of numpy warning. As I have numpy 1.15 installed.
Also, I have make sure all other dependencies are installed properly.
I have also installed cupy-cuda91( for my cuda 9.1 environment)

Thanks

**Comment by fiarabbit** [comment]
@shubham-IISc For the first image, ALL of the error message is related to the incompatibility between scipy and numpy (irrelevant to chainer). See [this stackoverflow for detail](https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility). In short, you can avoid the warning by installing scipy without binary.

For the second image, I could not get enough information from it. You can try it with another environment without installing scipy, because the incompatibility of numpy/scipy can cause the core dump.
