### ISSUE TITLE
Signal trigger

### ISSUE THREAD

**Issue by kuenishi** [chainer/chainer#5383]
Some container schedulers send SIGTERM and give grace period (later SIGKILL comes) to close resources or to take a snapshot of working job. It would be nice if Trainer have trigger for signals.

**Comment by kuenishi** [comment]
c.f. https://github.com/chainer/chainer/pull/2646

**Comment by kmaehashi** [comment]
To decide priority for this issue, could you elaborate your usecase a little more?
Regarding the snapshot, my primary concern is "grace period" may often not enough to complete the current iteration, take snapshot, and then exit gracefully.

**Comment by kuenishi** [comment]
The primary use case is for job preemption by cluster schedulers, interrupted by jobs with higher priority. For efficient snapshot preserving, right before preemption is the best time to take a snapshot. Then a scheduler can automatically resume the preempted job by the system, without bothering job owner to restart the job.

cc @everpeace @dtaniwaki

**Comment by dtaniwaki** [comment]
I think @kmaehashi 's concern is right. As he mentioned, we can't guarantee completion of taking a snapshot within a grace period. So the best strategy is taking snapshots periodically and try to take the latest snapshot by a signal such as `SIGTERM`. However, there's a possibility that taking a snapshot at an arbitrary timing during one epoch is not good if you can't save your rand seed and restore it correctly.

I think handling signals are still useful for other purposes. For example, if an ML job is reaching at 99% progress and it can finish during a grace period when it gets a signal, you can make the job try to continue running. Otherwise, you can make it give up immediately.

**Comment by kmaehashi** [comment]
As for k8s cluster, maybe it is possible to translate the signal:

1. Set terminationGracePeriodSeconds to relatively larger value
2. Set preStop hook to invoke `kill -USR1 PID; sleep inf` (where PID is a training python process)
3. Training python process catch the signal and exit gracefully 

End users can choose whether to:
- take snapshot in every iteration (for important jobs or heavy jobs that exceeds the grace period), or
- take snapshot only when SignalHandler is triggered

**Comment by kmaehashi** [comment]
cc/ @ryotarai

**Comment by kuenishi** [comment]
I think we can change our signal handler behaviour to wait for iteration completion and taking snapshot right after finish, during the grace period time. The snapshot won't be as much as GBs so it should be feasible and realistic to save snapshot within 30 or 60 seconds to any filesystem.

**Comment by kuenishi** [comment]
Most use cases are covered by https://github.com/chainer/chainer/pull/4630 , but `KeyboardInterrupt` is not handled yet...
