### ISSUE TITLE
Iterating over ChainerX array using `SerialIterator` degrades performance

### ISSUE THREAD

**Issue by okapies** [chainer/chainer#5897]
## Environment
  - Chainer version: master branch (`4eec402`)
  - CuPy version: 6.0.0b1
  - OS/Platform: Ubuntu 16.04.4 LTS
  - CUDA/cuDNN version: v7.2.1-cuda92

## Details
I tried to retrieve batches from a dataset (MNIST images; `(60000, 768)`) loaded in ChainerX array by using `SerialIterator`, but faced the performance degradation. Here is a [script](https://gist.github.com/okapies/bc5ffff3e13d6a76be9c8f19d0e333c3) to reproduce the issue.

e.g.

```
$ python3 chainer_iter_perf.py 
numpy array: 0.3922594524919987
cupy array: 1.742907416075468
chainerx (native) array: 70.63182811066508
chainerx (cuda) array: 77.44235955923796
genuine chainerx impl with shuffle (on cuda): 2.523347921669483
```

**Comment by grafi-tt** [comment]
The performance drop is due to fallback of `__getitem__`. ChainerX array doesn't accept `numpy.int64` value as an integer index. So the native `Array::At` method raises a C++ error, invoking time-consuming exception handling, then the indexing is handled by fallback mechanism for fancy indexing support.

The following patch solves the issue. But I'm not to send a PR, because the patch is just ad-hoc, and I don't understand ChainerX enough to provide a correct patch.

```
diff --git a/chainer/iterators/serial_iterator.py b/chainer/iterators/serial_iterator.py
index d9007026e..e7d0752c0 100644
--- a/chainer/iterators/serial_iterator.py
+++ b/chainer/iterators/serial_iterator.py
@@ -75,7 +75,7 @@ class SerialIterator(iterator.Iterator):
         if indices is None:
             raise StopIteration
 
-        batch = [self.dataset[index] for index in indices]
+        batch = [self.dataset[int(index)] for index in indices]
         return batch
 
     next = __next__
```

Benchmark result after applying the patch:

```
numpy array: 0.5380349730003218
cupy array: 4.296986602999823
chainerx (native) array: 1.6946163450011227
```

**Comment by niboshi** [comment]
@grafi-tt 
Thank you for suggestion.
I rather fixed the issue by supporting NumPy integers in `chainerx.ndarray.__getitem__`. (#5989)
