### ISSUE TITLE
chainer.Sequential stores links in a non-intuitive order

### ISSUE THREAD

**Issue by ktns** [chainer/chainer#6053]
Hi, I noticed that `chainer.Sequential` stores links in a non-intuitive order in `self._children`.

```python
import chainer

seq = chainer.Sequential()
for i in range(6):
    l = chainer.links.Linear(1, 1, initial_bias=i)
    seq.append(l)

[int(l.b.data[0]) for l in seq._children]  # => [0, 5, 4, 3, 2, 1]
[int(l.b.data[0]) for l in seq._layers]  # => [0, 1, 2, 3, 4, 5]
```
As far as I understand, this might be due to [this loop](https://github.com/chainer/chainer/blob/117095a7ac7660aa635670594b4efce5847ab178/chainer/sequential.py#L289-L292) is missing `break` statement.

I think it's better to fix this behavior, but I also think many existing npz files depend on this behavior.

What do you think about this issue?

**Comment by ktns** [comment]
If a compatibility-breaking change will be introduced, I would rather like a scheme like `self._children = filter(lambda l: isinstance(l, chainer.Link), self._layers)` than current numbering scheme.

**Comment by beam2d** [comment]
With some insertion/deletion patterns, `Sequential` of the same layer configuration may have different serialization order, which is not good either. I would like to fix this issue, but we also need to take care of serialization compatibility, which is highly important. One option is to introduce versioning to the serialization of `Sequential` so that the ordering is fixed while the old serialization data is still loadable.
