### ISSUE TITLE
`gc_interval` never used in `_MultiNodeCheckpointer`

### ISSUE THREAD

**Issue by nai62** [chainer/chainer#6232]
`gc_interval` seems to be never used in `_MultiNodeCheckpointer` and to have no effect.
`cp_interval` is used twice. Possibly one of them should be `gc_interval` instead?

One more thing I wonder is what this value '5' is intended for:
https://github.com/chainer/chainer/blob/master/chainermn/extensions/checkpoint.py#L160
Why is it 5 rather than 0?

**Comment by kuenishi** [comment]
I think that line should be `len(self.files) > gc_interval` instead. I think I just missed it during the dev and review process. Thank you for reporting.

Also `5` is kind of safety margin in case of inconsistency or partial lost among workers, in order to 
 step back to older version of snapshot when snapshot files are partially lacking.

**Comment by kuenishi** [comment]
The team has made a decision to deprecate multinode *checkpointer* ( https://github.com/chainer/chainer/pull/8207 ) and this issue won't be fixed. Instead, please use `multinode_snapshot` ( https://github.com/chainer/chainer/pull/8003 )  which is more efficient.
