### ISSUE TITLE
Convert Utilities docs to one page

### ISSUE THREAD

**Issue by Crissman** [chainer/chainer#6447]
Utilities Reference has several pages with one or two classes on it. Should convert to one page, and add `force_array` and `force_type` to it.

**Comment by trancenoid** [comment]
@Crissman I would like to work on this issue. I just need to know where to modify the Docs to accustom the changes.

**Comment by trancenoid** [comment]
@Crissman I have seen the sphinx docs and how to modify .rst files. If I understand the problem correctly we have to move all the classes onto one page (under different headings) instead of separate pages. Shall I do this job?

**Comment by Crissman** [comment]
Sure. Thanks!

**Comment by trancenoid** [comment]
Docs are built successfully, but I am getting warnings like this

`d:\chainer\chainer\utils\conv.py:docstring of chainer.utils.get_deconv_outsize:1: WARNING: duplicate object description of chainer.utils.get_deconv_outsize, other instance in d:\chainer\docs\source\reference\generated\chainer.utils.get_deconv_outsize.rst, use :noindex: for one of them`

This is the relevant part in modified util.rst

`
Convolution/Deconvolution utilities
-----------------------------------

.. autosummary::
   :toctree: generated/
   :nosignatures:

   chainer.utils.get_conv_outsize
   chainer.utils.get_deconv_outsize
   `

How do I fix this?

**Comment by trancenoid** [comment]
@Crissman please review my PR. I need documentation for force_array & force_type to add them to utilities, where can I get them?

**Comment by crcrpar** [comment]
Current implementations seem to lack the detailed documentation partially because those two functions are mainly used internally.

However, `force_array` is mentioned [here](https://docs.chainer.org/en/stable/reference/variable.html?highlight=force_array#n-dimensional-array), so I think it's welcomed to add documentation to the functions.

---
- force_array: https://github.com/chainer/chainer/blob/master/chainer/utils/__init__.py#L33
- force_type: https://github.com/chainer/chainer/blob/master/chainer/utils/__init__.py#L50
