### ISSUE TITLE
Performance regression in `allreduce_grad` in Chainer 5.2 -> 6.0 w/fp16

### ISSUE THREAD

**Issue by kuenishi** [chainer/chainer#7543]
We've observed performance regression between 5.2 and 6.0 in our internal cluster at `allreduce_grad` with fp32 model.  Benchmark code: https://github.com/chainer/comm_bench

6.0
![スクリーンショット_2019-06-18_15-46-19](https://user-images.githubusercontent.com/11440/59661308-7d770080-91e5-11e9-8b5b-5725b250f468.png)

5.2
![スクリーンショット_2019-06-18_16-22-16](https://user-images.githubusercontent.com/11440/59661317-82d44b00-91e5-11e9-9945-613fda1b5b42.png)

cc: @shu65

**Comment by shu65** [comment]
The problem may be solved if we do the following.
https://github.com/chainer/chainer/blob/master/chainer/optimizer.py#L201

**Comment by kuenishi** [comment]
Also, performance improved drastically with `batched_copy=True` .

**Comment by belldandyxtq** [comment]
We have confirmed the issue, and figured out that it is caused by massive implicit `cupy.copy` invoked by `astype` at https://github.com/chainer/chainer/blob/3a6e9ad0baf58175ba3e71459007fd13c134715c/chainermn/communicators/_memory_utility.py#L121
As we have batched_copy, a cuda kernel, to do the type casting in a much faster way, we have decided to make batched_copy default and available in all the communicators.

**Comment by belldandyxtq** [comment]
TODO:

- [ ] Apply batched_copy to all the communicators (#7761 )
- [ ] Switch to use batched_copy as default

**Comment by belldandyxtq** [comment]
solved by #7885
