### ISSUE TITLE
`use_fp32_update` does not use the current data

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7739]
https://github.com/chainer/chainer/blob/v7.0.0b1/chainer/optimizer.py#L200

`fp32_param.array` is not set except for the first call.

Code to reproduce:
```python
import chainer
import numpy

param = chainer.Parameter(numpy.array([2, 3], dtype='float16'))
param.grad = numpy.array([1, 2], dtype='float16')

class MyUpdateRule(chainer.UpdateRule):
    def update_core(self, param):
        print("update_core: ", param)
        param.array[...] += 1

update_rule = MyUpdateRule()
update_rule.use_fp32_update()

# First update
update_rule.update(param)

# Modify parameter manually
param.array = numpy.array([20, 30], dtype='float16')

# Second update
update_rule.update(param)  # The modification is lost
print(param)
```
Result
```
update_core:  variable([2. 3.])
update_core:  variable([3. 4.])
variable([4. 5.])
```

**Comment by beam2d** [comment]
With the current design, it needs readonly cupy array to detect if the array diverges from the cached version. Even if cupy supports it, the error message might be confusing.

One idea to avoid this problem is to adopt a completely different approach of fp32 update. This is actually used by other frameworks like Apex. In this design, models keep fp32 parameters directly, and whenever using them, these parameters are automatically cast to fp16. The cast is done in a differentiable manner. There is no cache mechanism in this case, so we don't need to deal with the cache coherency problem.
