### ISSUE TITLE
`--cupy-no-cuda` does not work

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#784]
I tried to install chainer with `--cupy-no-cuda`, but cupy was installed. This option doesn't work.

**Comment by delta2323** [comment]
`--cupy-no-cuda` option is not for disabling to install CuPy but for install CuPy to non-CUDA environment. So this behavior does not contradict to we suppose.

**Comment by unnonouno** [comment]
OK, it's confusing. This option is for read-the-docs. Use simpler name, such as `--for-rtd`. This option is not for users.

**Comment by unnonouno** [comment]
BTW, we need to make a method to disable cupy. Of course splitting repositories is enough.

**Comment by delta2323** [comment]
We need two information (i) this option is for RTD environment and (ii) what this option is doing (i.e. to install CuPy to non-CUDA environment). Currently we have the latter only.

One of the possible change is to change the option name so that it reflect (i) (like `--for-rtd`) and add description about (ii). The other alternative is vice versa. Both are OK for me.

**Comment by delta2323** [comment]
Do you have urgent need for installation without cupy? If not, I think we can defer it until CuPy is separated from Chainer.

**Comment by beam2d** [comment]
How about `--force-install-cupy`?

**Comment by delta2323** [comment]
@unnonouno Is this problem solved after CuPy separation?
