### ISSUE TITLE
Flaky test: tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py::test_CholeskyFailing

### ISSUE THREAD

**Issue by asi1024** [chainer/chainer#8362]
Occurred in #8342 

https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2387/TEST=CHAINERX_chainerx-py3,label=mn1-p100/console

**Comment by emcastillo** [comment]
The test is funny, it is set to accept  this exact error in forward, but if none of the errors happens,
backward is called. 
The matrix to call backward was not positive definite so it failed calling forward when doing the gradient computations because this error was not checked 😂.

**Comment by toslunar** [comment]
A random symmetric 6×6 matrix can be positive definite by chance.

**Comment by emcastillo** [comment]
Yes, I think we need to generate matrices that always produce the fail instead of leaving it to luck.

Right now the generated matrix passes the forward test without errors (if an error happens backward wont be called), but sometimes when the result is applied to backward
then we are getting this failure because the backward is doing the calculation on a non positive definite matrix.
