### ISSUE TITLE
A problem about update method of Chainermn's multi-node optimizer

### ISSUE THREAD

**Issue by homer12** [chainer/chainer#8510]
Sorry, I hava a problem using the multi-node optimizer of chainermn.

The setting of my environment is below:
- Version: 6.2.0
- OS/Platform: Ubuntu 18.04
- Dataset: Cifar-10
- Network Model: VGG16
- GPU: one server with 4 Tesla V100

I was using the [_MultiNodeOptimizer](https://github.com/chainer/chainer/blob/a3c428a32905052e33fc6427f5bfd8ae4b782f79/chainermn/optimizers.py#L5) of Chainermn to train my model.
And I was measuring the time for the [update](https://github.com/chainer/chainer/blob/a3c428a32905052e33fc6427f5bfd8ae4b782f79/chainermn/optimizers.py#L17) method of this multi-node optimizer. 
I broke the time to three parts:
1. Time for forward and backword propagation, which consists of the lines from [calculating of loss](https://github.com/chainer/chainer/blob/a3c428a32905052e33fc6427f5bfd8ae4b782f79/chainermn/optimizers.py#L21) to [backward](https://github.com/chainer/chainer/blob/a3c428a32905052e33fc6427f5bfd8ae4b782f79/chainermn/optimizers.py#L26).
2. Time for networking (allreduce). It is mostly the [allreduce_grad](https://github.com/chainer/chainer/blob/a3c428a32905052e33fc6427f5bfd8ae4b782f79/chainermn/optimizers.py#L32) performed by the MPI communicator.
3. Time for updateing the parameters of model. This is performed by the [updte method](https://github.com/chainer/chainer/blob/a3c428a32905052e33fc6427f5bfd8ae4b782f79/chainermn/optimizers.py#L33) of the actual optimizer.

Then I tried to change the batch size from 128/iter to 512/iter.
I thought that the networking time would **remain the same** even with bigger batch size.( Since we only need to allreduce the gradient of model, right? So It was supposed that the networking time has noting to do with the batch size)
And propagation and update time will **increase** since the model has to process more images in one iteration.

But it turned out that what I thougt was totally wrong.
Below is the result that I got ( I used `time.perf_counter` method to measure the time ):
- batch size: 128 -> 512
- forward/backward propagation: 0.017s -> 0.010s
- network(allreduce) time: **0.035s -> 0.167s**
- update time: 0.0056s -> 0.0034s

Not only the networking time increased, the learning time of model also decreased surprisingly.

So, it would be greatly appreciated that if any one can tell me the cause.
Was my assumption wrong?
Or Chainer was not implemented like I thought?

Thank you very much.

P.S.: I can read Japanese, so it's ok to reply in Japanese. よろしくお願いいたします。

**Comment by keisukefukuda** [comment]
Hi, 
Are you using `PureNCCLCommunicator`, or `FlatCommunicator` ?

If you are using NCCL, the communication is actually asynchronous. Thus, the communication time cannot be measured using CPU-side performance analyzer, including `time.perf_counter`.

You need `nvprof` to measure/observe what's happening in the GPU. 

My guess is that a larger batch size leads to a larger variance in the forward/backward processing time. Since the communication happens asynchronously from CPU side processing, and a synchronization point is at the end of a single batch.

One thing worth trying to find what's going on is to use an ordinary `Optmizer` class instead of `MultinodeOptimizer` while invoking via MPI. What happens here is that each MPI process processes a batch independently without any communication, so you can measure how forward/backward time change by increasing the batch size and compare the result to the original experiment you have done. 

Thanks!.

**Comment by homer12** [comment]
Thank you for the reply and advice!

Do you think that it will work if I use `HirearchicalCommunicator` or `FlatCommunicator` instead of `PureNcclCommunicator` ?

Thanks.

**Comment by keisukefukuda** [comment]
Hello,

If you are using HierarchicalCommunicator or FlatCommunicator, the technique to replace `MulitnodeOptimizer` with normal `Optimizer` works. `nvprof` still helps, but it's only for the computation.

(BTW, we recommend `FlatCommunicator` if you use MPI only. `HierarchicalCommunicator` was developed when NCCL version was 1.x, and it does not make sense to use it nowadays)

**Comment by keisukefukuda** [comment]
Do not hesitate to reopen the issue if you still have an issue. Thanks!
